"""Unified facet vocabulary banks for domain-agnostic vibe detection."""

from pydantic import BaseModel, Field

# Single unified vocabulary for all facets.
# color is populated from classical CV (k-means + perceptual names), not zero-shot.
FACET_VOCABULARIES: dict[str, list[str]] = {
    "style": [
        "midcentury",
        "scandi",
        "industrial",
        "boho",
        "farmhouse",
        "japandi",
        "art_deco",
        "minimalist",
        "traditional",
        "transitional",
        "contemporary",
        "cottagecore",
        "outdoorsy",
        "gorpcore",
        "nautical",
        "safari",
        "western",
        "streetwear",
        "grunge",
        "punk",
        "gothic",
        "glam",
        "preppy",
        "dark_academia",
        "y2k",
        "tropical",
        "coquette",
        "old_money",
        "witchy",
        "vaporwave",
        "cyberpunk",
        "indie_sleaze",
        "balletcore",
        "fairycore",
        "mermaidcore",
        "e_girl",
        "clean_girl",
        "light_academia",
        "goblincore",
        "dreamcore",
        "angelcore",
        "barbiecore",
        "normcore",
        "cabincore",
        "cluttercore",
        "regencycore",
        "tenniscore",
    ],
    # Natural landscape / biome — distinct from "style" so a mountain photo
    # isn't forced to compete against interior-design and subculture labels.
    "terrain": [
        "desert",
        "tundra",
        "rainforest",
        "savanna",
        "canyon",
        "glacier",
        "volcanic",
        "woodland",
        "wetland",
        "highland",
        "dune",
        "fjord",
        "meadow",
        "alpine",
        "coastal",
    ],
    # Built environment / civic setting.
    "locale": [
        "skyline",
        "downtown",
        "suburban",
        "urban",
        "park",
        "plaza",
        "boardwalk",
        "promenade",
        "courtyard",
        "rooftop",
        "metropolitan",
        "historic_district",
        "waterfront",
        "garden",
        "botanical",
    ],
    "shape": [
        "rounded",
        "angular",
        "curved",
        "boxy",
        "sculptural",
        "oversized",
        "compact",
        "asymmetric",
        "symmetrical",
        "fluid",
        "chunky",
        "sleek",
        "bulky",
        "geometric",
    ],
    "material": [
        "wood",
        "rattan",
        "brass",
        "linen",
        "concrete",
        "velvet",
        "marble",
        "wicker",
        "leather",
        "ceramic",
        "glass",
        "steel",
        "bamboo",
        "terrazzo",
        "stone",
        "granite",
        "slate",
        "fur",
        "wool",
        "flannel",
        "canvas",
        "denim",
        "cork",
        "cotton",
        "silk",
        "suede",
        "gold",
        "copper",
        "clay",
        "paper",
    ],
    "quality": [
        "cozy",
        "serene",
        "dramatic",
        "energetic",
        "moody",
        "airy",
        "eclectic",
        "rugged",
        "polished",
        "organic",
        "structured",
        "layered",
        "sparse",
        "minimal",
        "wild",
        "crisp",
        "misty",
        "weathered",
        "raw",
        "pristine",
        "vibrant",
        "somber",
        "ethereal",
        "gritty",
        "nostalgic",
        "futuristic",
        "earthy",
        "lush",
        "barren",
        "tranquil",
        "vast",
        "whimsical",
        "golden",
        "icy",
        "arctic",
        "oceanic",
        "sunset",
        "sky",
        "windswept",
        "craggy",
        "verdant",
        "arid",
        "humid",
        "panoramic",
        "remote",
        "untouched",
        "overcast",
        "foggy",
    ],
}


class FacetProfile(BaseModel):
    """Structured facet values for a set of images.

    Each facet holds a ranked top-k list of tags rather than a single winner,
    so a forced single choice doesn't drown out real ambiguity in the image
    (e.g. a scene that's plausibly both "moody" and "serene").
    """

    style: list[str] = Field(default_factory=list)
    terrain: list[str] = Field(default_factory=list)
    locale: list[str] = Field(default_factory=list)
    material: list[str] = Field(default_factory=list)
    color: list[str] = Field(default_factory=list)
    quality: list[str] = Field(default_factory=list)
    shape: list[str] = Field(default_factory=list)

    def surviving_facets(self) -> dict[str, list[str]]:
        """Return only facets that have at least one surviving value."""
        return {k: v for k, v in self.model_dump().items() if v}
